# Generated by Django 5.0.7 on 2024-07-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='users/'),
            preserve_default=False,
        ),
    ]
